api/urls.py
from django.urls import path

from . import views

app_name='api'

urlpatterns=[
    path('products/<int:pk>/', views.ProductDetailView.as_view()),
    path('products/', views.products),
    path('categories/<int:pk>/', views.CategoryDetailView.as_view()),
    path('categories/', views.categories),

]

avtosticker2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace = 'shop')),
    path('api/', include('api.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders'))
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name= 'cart_add'),
    path('plus/<int:product_id>/', views.cart_plus, name= 'cart_plus'),
    path('minus/<int:product_id>/', views.cart_minus, name= 'cart_minus'),
    path('remove/<int:product_id>/', views.cart_remove, name= 'cart_remove'),
    path('del/', views.cart_del, name='cart_del'),
   	
]

orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name = "order_create"),
    path('admin/order/<int:order_id>/pdf/', views.admin_order_pdf, name='admin_order_pdf'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms



PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 100)]

class CartAddProductForm(forms.Form):

    plus = forms.BooleanField(required=False,
                                initial=False,
                              widget=forms.HiddenInput)
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int,
        label=('Quantity'),
        widget= forms.NumberInput
    )

    minus = forms.BooleanField(required=False,
                                initial=False,
                               widget=forms.HiddenInput)


    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST
from django.conf import settings

from shop.models import Product, Category
from .cart import Cart
from .forms import CartAddProductForm


@require_POST

def cart_add(request, product_id ):
    cart=Cart(request)
    product= get_object_or_404(Product, id= product_id)
    form = CartAddProductForm(request.POST)


    if form.is_valid():
        cd = form.cleaned_data

        cart.add(product=product,
                 quantity=cd['quantity'],

                 update_quantity=cd['update'])


    return redirect('cart:cart_detail')

def cart_plus(request, product_id ):
    cart=Cart(request)
    product= get_object_or_404(Product, id= product_id)
    form = CartAddProductForm(request.POST)
    cart.plus(product=product,
                 quantity=['quantity'],
                 plus=['plus'],
                 )
    return redirect('cart:cart_detail')

def cart_minus(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    cart.minus(product=product,
              quantity=['quantity'],
              minus=['minus'],
              )
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_del(request):
    cart = Cart(request)
    del cart.session[settings.CART_SESSION_ID]
    cart.save()
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart=Cart(request)
    categories = Category.objects.all()
    for item in cart:

        item['update_quantity_form'] = CartAddProductForm(
            initial={'quantity': item['quantity'],
                     'plus': True,
                     'minus': True,
                     'update': True,
                     }
        )

    return render(request, 'cart/detail.html', {'cart': cart,
                                                'categories': categories,

                                                 })

cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% load thumbnail %}

{% block title %}
  Your shopping cart
{% endblock %}

{% block sidebar %}
    {% include "shop/inc/_nav.html" %}
{% endblock %}

{% block content %}
  <h1>Your shopping cart</h1>
  <table class="cart">
    <thead>
      <tr>
        <th>Image</th>
        <th>Product</th>
        <th>Quantity</th>
        <th>Remove</th>
        <th>Unit price</th>
        <th>Price</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        {% with product=item.product %}

            <td>
              <a href="{{ product.get_absolute_url }}">

                <img src="{% if product.image %}{% thumbnail product.image 'small' %}{% else %}{% static "img/no_image.png" %}{% endif %}">

              </a>
            </td>
            <td>{{ product.name }}</td>


<td>
              <form size="small" action="{% url "cart:cart_minus" product_id=product.id %}" method="post">


               {{ item.update_quantity_form.minus }}
              <input size="small" type="submit" value="-">

                  {% csrf_token %}
              </form></td>
            <td>  <form action="{% url "cart:cart_add" product_id=product.id %}" method="post">
              {{ item.update_quantity_form.quantity }}
                  {{ item.update_quantity_form.update }}
                  <input type="submit" value="Update">
                  {% csrf_token %}
              </form></td>
             <td> <form action="{% url "cart:cart_plus" product_id=product.id %}" method="post">
                  {{ item.update_quantity_form.plus }}
                  <input type="submit" value="+">
                  {% csrf_token %}
              </form></td>




            <td><a href="{% url "cart:cart_remove" product_id=product.id %}">Remove</a></td>
            <td class="num">${{ item.price }}</td>
            <td class="num">${{ item.total_price }}</td>
          </tr>
        {% endwith %}
      {% endfor %}
      <tr class="total">
        <td>Total</td>
        <td colspan="4"></td>
        <td class="num">${{ cart.get_total_price }}</td>
      </tr>
    </tbody>
  </table>
  <p class="text-right">
    <a href=" / " class="button light">Continue shopping</a>
    <a href="{% url "orders:order_create" %}" class="button" >
      Checkout
    </a>
  </p>
    <p><a href="{% url 'cart:cart_del' %}">Очистити корзину</a></p>
{% endblock %}

cart/templates/cart/navcart.html
<li class="nav-item active">
        <a class="nav-link" href="{% url "cart:cart_detail" %}">Кошик <span class="sr-only">(current)</span></a>
      </li>