api/urls.py
from django.urls import path

from . import views

app_name='api'

urlpatterns=[
    path('products/<int:pk>/', views.ProductDetailView.as_view()),
    path('products/', views.products),
    path('categories/<int:pk>/', views.CategoryDetailView.as_view()),
    path('categories/', views.categories),

]

avtosticker2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace = 'shop')),
    path('api/', include('api.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders'))
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name= 'cart_add'),
    path('plus/<int:product_id>/', views.cart_plus, name= 'cart_plus'),
    path('minus/<int:product_id>/', views.cart_minus, name= 'cart_minus'),
    path('remove/<int:product_id>/', views.cart_remove, name= 'cart_remove'),
    path('del/', views.cart_del, name='cart_del'),
   	
]

shop/urls.py
from django.urls import path
from .import views

app_name = 'shop'

urlpatterns = [
    path('', views.test, name='test'),
#    path('category/<int:pk>/', views.CategoryViews.as_view(), name='category_list'),
#    path('', views.product_list, name='product_list'),
#    path('category/<int:parent_id>/', views.category_list2, name='category_list2'),
    path('category/<slug:slug>/', views.show_category, name='category_list'),
    path('category2/<slug:slug>/', views.category_list_child, name='category_list_child'),
#    path('product/<int:pk>/', views.product_detail, name='product_detail'),
    path('product/<int:pk>/<slug:slug>/', views.product_detail, name = 'product_detail'),
#    path('product/<int:pk>/', views.ProductViews.as_view(), name = 'product'),
]

shop/models.py
from django.db import models
from django.urls import reverse
from mptt.models import MPTTModel, TreeForeignKey

class Category(MPTTModel):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children', db_index=True)

    class MPTTMeta:
        order_insertion_by = ['name']

    class Meta:
        ordering = ('name',)
        index_together = (('parent', 'slug'),)
        verbose_name = 'Категорія'
        verbose_name_plural = 'Категорії'

    def get_slug_list(self):
        try:
            ancestors = self.get_ancestors(include_self=True)
        except:
            ancestors = []
        else:
            ancestors = [i.slug for i in ancestors]
        slugs = []
        for i in range(len(ancestors)):
            slugs.append('/'.join(ancestors[:i + 1]))
        return slugs

    def __str__(self):
        return self.name





    def get_absolute_url(self):
        return reverse('shop:category_list', kwargs={ "category_slug": self.slug})

class Product(models.Model):
    category = TreeForeignKey(Category,
                                 related_name="products",
                                 on_delete=models.CASCADE,
                                 verbose_name = 'Категорія')
    name = models.CharField(max_length=200, db_index=True, verbose_name = 'Назва товару')
    slug = models.SlugField(max_length=200, unique=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True, verbose_name = 'Зображення')
    description = models.TextField(blank=True, verbose_name = 'Опис товару')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name = 'Ціна')
    avialable = models.BooleanField(default=True, verbose_name = 'Наявність продукту')
    created = models.DateTimeField(auto_now_add=True, verbose_name = 'Дата створення')
    updated = models.DateTimeField(auto_now=True, verbose_name = 'Дата останнього редагування')
    views = models.IntegerField(default=0, verbose_name = 'Кількість переглядів')

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукти'

    def __str__(self):
        return  self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', kwargs={'pk':self.id, 'slug':self.slug})

shop/views.py
from django.shortcuts import render, get_object_or_404
from django.template import loader, Context, RequestContext
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


from django.http import Http404, HttpResponse

from .models import Category, Product
from cart.forms import CartAddProductForm

def test(request):
    return render(request, "shop/home.html", {'categories': Category.objects.all()})


def product_list(request):
    def product(request,  slug):
        product = get_object_or_404(Product,  slug=slug)
#        cart_product_form = CartAddProductForm()
        categories = Category.objects.all()
        return render(request, 'shop/category_list.html',
                      {'product': product,
 #                      'cart_product_form': cart_product_form,
                       'categories': categories,
                       })




def category_list_child(request, slug = None):
    category = get_object_or_404(Category, slug=slug)
#    category = Category.objects.get(pk = category_id)

    products = Product.objects.filter(category__slug=slug)

#    category = get_object_or_404(Category, pk = category_id)
#    if pk:
#        category = get_object_or_404(Category, pk = pk)
#        products = Product.objects.filter(category= category)

    paginator = Paginator(products, 8)
    page = request.GET.get('page')
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        products = paginator.page(1)
    except EmptyPage:

        products = paginator.page(paginator.num_pages)

    return render(request, 'shop/category_list_child.html',
                  {'category': category,
                   'products':products,
                   'page':page

                   })

def category_list(request, category_id):
    category = Category.objects.get_children(pk=category_id)

    products = Product.objects.filter(category_id=category_id)

 #   parent_primary_keys = Category.objects.filter(pk = root_category_id).values_list('pk', flat=True)

#    products = Product.objects.filter(id__in=parent_primary_keys)



 #   category = Category.objects.get(slug = category_slug)
 #   products = Product.objects.filter(category= category)

 #   category = Category.objects.get(id=category_id)
 #   root_category_id = category.get_root().id

#    pr = Product.objects.all()
#    products = pr.filter(category_id=root_category_id)



#    category = get_object_or_404(Category, pk = category_id)
#    if pk:
#        category = get_object_or_404(Category, pk = pk)
#        products = Product.objects.filter(category= category)

    return render(request, 'shop/category_list.html',
                  {'nodes':Category.objects.all(),
 #                             'category':category,
  #                            'categories': categories,

                   'products': products,


                   })


def product_detail(request, pk, slug):
    product = get_object_or_404(Product, pk=pk,  slug=slug)
 #   category = get_object_or_404(Category, slug=slug)
    cart_product_form= CartAddProductForm()
    categories = Category.objects.all()
    return render(request, 'shop/detail.html',
                  {'product': product,
                   'cart_product_form': cart_product_form,
                    'categories':categories,
#                   'category': category
                   })

def show_category(request,  slug ):
    category_slug = slug.split('/')
    parent = None
    root = Category.objects.all()

    for slug in category_slug:
        parent = root.get(parent=parent,  slug = slug)
#        products = get_object_or_404(Product, slug=category_slug[-1])
#        return render(request, 'shop/categories.html', {
#                                                        'products': products})
#        products = Product.objects.filter(category__slug=slug)

#    try:
#        instance = Category.objects.get(parent=parent,slug=category_slug[-1])

#    except:
    instance = get_object_or_404(Category, slug = category_slug[-1])
    products = Product.objects.filter(category__parent=parent)

    paginator = Paginator(products, 8)
    page = request.GET.get('page')
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        products = paginator.page(1)
    except EmptyPage:

        products = paginator.page(paginator.num_pages)
    return render(request, "shop/category_list.html", {'instance':instance,
                                                           'products': products,
                                                       'page':page})
#    else:
#        products = Product.objects.filter(slug='znaki')
#        return render(request, 'shop/base.html', {'instance':instance,
#                                                       'products':products })

shop/templates/shop/base.html
{% load static %}
{% load bootstrap4 %}
{% load mptt_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <title>{% block title %}Інтернет магазин автонаклеєк{% endblock %}</title>
    <link href="{% static "css/base.css" %}" rel="stylesheet">
    <script src="/static/js/base.js"></script>
</head>
<body>

<nav class="navbar navbar-expand-md bg-dark navbar-dark" style="margin: 1rem 1rem 1rem 1rem">
  <a class="navbar-brand" href="/">Головна</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="collapsibleNavbar">
    <ul class="navbar-nav">
      {% if request.user.is_authenticated %}

         <li class="nav-item active">
        <a class="nav-link" >Привіт {{ request.user.username }} ! </a>
      </li>

         <li class="nav-item active">
        <a class="nav-link" href="#">Вихід </a>
      </li>

          <li class="nav-item active">
        <a class="nav-link" href="#">Профіль</a>
      </li>

     {% else %}
        <li class="nav-item active">
        <a class="nav-link" href="#">Вхід <span class="sr-only">(current)</span></a>
      </li>
        <li class="nav-item active">
        <a class="nav-link" href="#">Реєстрація <span class="sr-only">(current)</span></a>
      </li>

      {% endif %}



    </ul>



  </div>

{% include 'cart/navcart.html' %}


 <form action="#" method="get" class="form-inline my-2 my-lg-0">

      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Пошук</button>
    </form>
</nav>







<nav class="navbar navbar-expand-lg navbar-light bg-light" style="margin: 0 1rem 0.3rem 1rem" >
  <a class="navbar-brand" href="/" style="padding: 2px">ІНТЕРНЕТ МАГАЗИН</a>

  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">



    </ul>
    <span class="navbar-text">
     <div class="cart">
      {% with total_items=cart|length %}
                {% if cart|length > 0 %}
                    Ваша корзина:
                    <a href="{% url "cart:cart_detail" %}">
                      {{ total_items }} шт.  на суму
                      ₴ {{ cart.get_total_price }}
                    </a>
                {% else %}
                    Ваша корзина порожня.
                {% endif %}
            {% endwith %}
     </div>
    </span>
  </div>
</nav>

<div class="container-fluid" >
    <div class="row" style="margin: 0; padding: 0">
  <div class="sidebarbg  col-md-2">{% block sidebar %}




  {% endblock %}</div>
  <div class="contentbg  col-md-8" >{% block content %}{% endblock %}</div>
  <div class="sidebarbg  col-md-2">{% block rigthbar%}{% endblock %}</div>
</div>






<script src="https://code.jquery.com/jquery-3.4.1.min.js" ></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

<script src="{% static 'js/scripts.js' %}"></script>
</body>
</html>

shop/templates/shop/categories.html
{% extends 'shop/base.html' %}
{% load static  %}

{% block head_title %} {{ instance.name }} {% endblock %}

{% block content %}
<br>
<div class="text-center"><h2>{{instance.name}}</h2></div>

{% if  instance.children.all %}
    <h4>Sub Categories</h4>
    {% for i in instance.children.all %}
        <a href="{{ i.slug }}"> {{ i.name }} </a><br>

        rrrr
        {% for product in products %}
        qqq
        {% endfor %}
    {% endfor %}

    <br><hr>
{% endif %}

{% if  instance.post_set.all %}
 {% for i in instance.post_set.all %}
  <h4>Posts</h4>
  <div class="row small-up-1 medium-up-3" >

   <div class="column">
    <a href="{{ i.slug }}">
      <div class="card" style="width: 300px; border-color: black">
         <div class="card-divider">
           <strong>{{ i.name}}</strong>
         </div>

         <div class="card-section">
          <small>{{ i.publish}} </small>
          <p>{{ i.content | safe | truncatechars_html:120 }}</p>
         </div>
      </div>
    </a>
   </div>
{% endfor %}

{% endif %}
</div>
{% endblock %}

shop/templates/shop/category_list.html
{% extends 'shop/base.html' %}
{% load thumbnail %}
{% load static %}
{% load bootstrap4 %}

{% block sidebar %}
 {% include 'shop/category_tree.html' %}
{% endblock %}

{% block content %}

<div class="text-center"><h2>{{instance.name}}</h2></div>
    <div class="container-fluid">
        <div class="row">

{% if  instance.children.all %}


           {% for product in products %}
            <div class="col-12 col-sm-6 col-md-4 col-lg-3 "  >
                      <div class="shadow-img">
  <!--                    <div class="shadow p-0 mb-0 bg-black rounded"  >  -->
                          <a href="{{ product.get_absolute_url }}">
                          <img src="{% if product.image %}{% thumbnail product.image 'default' %}
                            {% else %}{% static "img/no_image.png" %}{% endif %}"
                         class="img-thumbnail  mx-auto d-block" style=" padding: 0" >
                         </a>

 <!--                       </div>  -->
                      </div>
                      <div>
                        <a  class="nameprice" href="{{ product.get_absolute_url }}">

                            <p class="text-center" style="margin-bottom: 0.01rem">    {{ product.name }} </p></a>
                          <span class="nameprice">

                          <p class="text-center" style="margin-bottom: 0.03rem">  {{ product.price }} грн.</p>
                          </span>
                          </div>
            </div>
        {% endfor %}

{% endif %}

</div>
    <input type="button" onclick="history.back();" value="Назад"/>
        </div>
      {% include "shop/inc/_pagination.html" with page=products %}
{% endblock %}

shop/templates/shop/category_list_child.html
{% extends 'shop/base.html' %}
{% load thumbnail %}
{% load static %}
{% load bootstrap4 %}

{% block sidebar %}
 {% include 'shop/category_tree.html' %}
{% endblock %}

{% block content %}




<h1 class="text-center">{% if category %}{{ category.name }}{% else %}Products{% endif %}</h1>



    <div class="container-fluid">
        <div class="row">
        {% for product in products %}
            <div class="col-12 col-sm-6 col-md-4 col-lg-3 "  >
                      <div class="shadow-img">
  <!--                    <div class="shadow p-0 mb-0 bg-black rounded"  >  -->
                          <a href="{{ product.get_absolute_url }}">
                          <img src="{% if product.image %}{% thumbnail product.image 'default' %}
                            {% else %}{% static "img/no_image.png" %}{% endif %}"
                         class="img-thumbnail  mx-auto d-block" style=" padding: 0" >
                         </a>

 <!--                       </div>  -->
                      </div>
                      <div>
                        <a  class="nameprice" href="{{ product.get_absolute_url }}">

                            <p class="text-center" style="margin-bottom: 0.01rem">    {{ product.name }} </p></a>
                          <span class="nameprice">

                          <p class="text-center" style="margin-bottom: 0.03rem">  {{ product.price }} грн.</p>
                          </span>
                          </div>
            </div>
        {% endfor %}
        </div>

<input type="button" onclick="history.back();" value="Назад"/>
    </div>
    {% include "shop/inc/_pagination.html" with page=products %}
{% endblock %}

shop/templates/shop/category_tree.html
{% load bootstrap4 %}
{% load mptt_tags %}



{% recursetree categories %}
  <div class="dropdown">
  <button class="btn btn-secondary dropright" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" >
    {{ node.name }}
  </button>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">

    <a class="dropdown-item" href="{% url 'shop:category_list'  node.slug %}">{{ node.name }}</a>
    {% for child in node.children.all %}
    <a class="dropdown-item" href="{% url 'shop:category_list_child'  child.slug %}">{{ child.name }}</a>
    {% endfor %}

  </div>
</div>
    <br>

 {% endrecursetree %}

shop/templates/shop/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% load thumbnail %}

{% block title %}
  {{ product.slug }}
{% endblock %}

{% block sidebar %}
    {% include "shop/inc/_nav.html" %}
{% endblock %}

{% block content %}
    <div class="container">
  <div class="product-detail">

    <img src="{% if product.image %}{% thumbnail product.image 'detail' %}{% else %}{% static "img/no_image.png" %}{% endif %}"
     class="img-thumbnail  d-block" >

    <h1>{{ product.name }}</h1>

    <p class="price">₴ {{ product.price }}</p>


  <form action="{% url "cart:cart_add" product_id=product.id   %}"  method="post" id="form_buying_product" class="form-inline">
     <input type="button" value="-" onClick="change('number',0,100,-1);"/>
      <div class="form-group">
     <input   class="form-control" name="number" id="number" value="1">

      </div>

    <div class="form-group">
<input type="button" value="+" onClick="change('number',0,100, 1);"/>
    <button type="submit" id="submit-btn" class="btn btn-outline-success btn-buy"
        data-product_id = "{{ product.id }}"
        data-product_name = "{{ product.name }}"
        data-quantity = "{{ quantity }}"
         data-product_price = "{{ product.price }}"

>

{% csrf_token %}


        КУПИТИ
    </button>
    </div>

  </form>

   <p class="text-right">

    <a href="/" class="button light">Купити ще...  </a>
       <a href="{% url "cart:cart_detail" %}" class="button" >   Перейти до кошика</a>


  </p>

  <br>





 <!--   <form action="{% url "cart:cart_add" product_id=product.id   %}"  method="post"  >

        {{ cart_product_form }}
        {% csrf_token %}


        <input  type="submit" value="Add to cart" class="btn btn-primary btn-buy">


    </form>  -->

    {{ product.description|linebreaks }}
     </div>
    <input type="button" onclick="history.back();" value="Назад"/>
    </div>


<form size="small" action="{% url "cart:cart_minus" product_id=product.id %}" method="post">


               {{ item.update_quantity_form.minus }}
              <input size="small" type="submit" value="-">

                  {% csrf_token %}
              </form></td>
            <td>  <form action="{% url "cart:cart_add" product_id=product.id %}" method="post">
              {{ update_quantity_form.quantity }}
                  {{ item.update_quantity_form.update }}
                 <input   class="form-control" name="number" id="number" value="1">
                  <input type="submit" value="Update">
                  {% csrf_token %}
              </form></td>
             <td> <form action="{% url "cart:cart_plus" product_id=product.id %}" method="post">
                  {{ item.update_quantity_form.plus }}
                  <input type="submit" value="+">
                  {% csrf_token %}
              </form></td>


{% endblock %}

shop/templates/shop/home.html
{% extends 'shop/base.html' %}
{% load bootstrap4 %}


{% block sidebar %}
 {% include 'shop/category_tree.html' %}
{% endblock %}

shop/templates/shop/product.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
Product
</body>
</html>

shop/templates/shop/test.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% load mptt_tags %}
<ul>
    {% recursetree categories %}
        <li>
            <a href="{{ node.get_absolute_url }}">{{ node.name }}</a>
            {% if not node.is_leaf_node %}
                <ul class="children">
                    {{ children }}
                </ul>
            {% endif %}
        </li>
    {% endrecursetree %}
</ul>

</body>
</html>